"""empty message

Revision ID: 0aa161bdbfd8
Revises: d7eee3cebc10
Create Date: 2025-01-28 18:54:50.364309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa161bdbfd8'
down_revision = 'd7eee3cebc10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro_stock', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['libro_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
