"""empty message

Revision ID: 5cb0716bf8a8
Revises: 0aa161bdbfd8
Create Date: 2025-01-29 12:33:29.412112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb0716bf8a8'
down_revision = '0aa161bdbfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliotecario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliotecario', schema=None) as batch_op:
        batch_op.drop_column('clave')

    # ### end Alembic commands ###
