"""empty message

Revision ID: ca14ac751b93
Revises: 5cb0716bf8a8
Create Date: 2025-01-29 12:47:20.299413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca14ac751b93'
down_revision = '5cb0716bf8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliotecario', schema=None) as batch_op:
        batch_op.alter_column('clave',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=65),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliotecario', schema=None) as batch_op:
        batch_op.alter_column('clave',
               existing_type=sa.String(length=65),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
