"""empty message

Revision ID: d7eee3cebc10
Revises: 3f9aa99d05b5
Create Date: 2025-01-28 18:19:18.736544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7eee3cebc10'
down_revision = '3f9aa99d05b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bibliotecario_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('prestamo_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'libro_stock', ['libro_id'], ['id'])
        batch_op.create_foreign_key(None, 'bibliotecario', ['bibliotecario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('prestamo_ibfk_2', 'libro', ['libro_id'], ['id'])
        batch_op.drop_column('bibliotecario_id')

    # ### end Alembic commands ###
