"""Creación clases

Revision ID: e196998d12e7
Revises: 
Create Date: 2025-02-01 17:09:42.549435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e196998d12e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bibliotecario',
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('clave', sa.String(length=65), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('prestados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('bibliotecario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bibliotecario_id'], ['bibliotecario.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamo')
    op.drop_table('libro')
    op.drop_table('cliente')
    op.drop_table('bibliotecario')
    # ### end Alembic commands ###
